# Generated by Django 4.1.1 on 2022-10-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_savedpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000)),
                ('content', models.CharField(max_length=5000)),
                ('url', models.URLField()),
                ('img', models.URLField()),
                ('publication_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='SavedPost',
        ),
        migrations.AddField(
            model_name='user',
            name='saved_articles',
            field=models.ManyToManyField(related_name='savers', to='articles.article'),
        ),
    ]
