# Generated by Django 4.1.1 on 2022-10-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_delete_savedpost_user_saved_articles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Saved_Article',
        ),
    ]
